version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: neoteric
    ports:
      - "3307:3306"  # Expose MySQL port

  spring-app:
    build: .
    container_name: spring_app
    ports:
      - "8082:8082"  # Expose Spring Boot app port
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/neoteric
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql  # Depend on the MySQL service
